name: mikoji_prison
description: A new Flutter project.
publish_to: "none"

version: 1.5.0

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  beamer: ^1.4.1+1
  cupertino_icons: ^1.0.2
  dartx: ^1.1.0
  dartz: ^0.10.1
  easy_localization: ^3.0.0
  flash: ^1.5.1
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^1.1.0
  flutter_uix: ^0.1.2-nullsafety.2
  freezed_annotation: ^2.0.3
  google_fonts: ^3.0.1
  hive_flutter: ^1.1.0
  hooks_riverpod: ^1.0.4
  flutter_hooks: ^0.18.4
  ionicons: ^0.1.2
  logger: ^1.1.0
  responsive_builder: ^0.4.1
  rive: ^0.8.4
  flare_flutter:
  rive_splash_screen: ^0.1.0
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/heros/
    - assets/images/mafia_heros/
    - assets/icons/
    - assets/flare/
    - assets/translations/
